# Generated by Django 5.1 on 2024-08-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_stokadjustment_stockadjustment'),
        ('products', '0002_product_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('product', 'location')},
        ),
    ]
