# Generated by Django 5.1 on 2024-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
